config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :events
  root 'welcome#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/alumni.rb
class Alumni < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :orders

  delegate :url_helpers, to: 'Rails.application.routes'

  default_scope { order(start_date: :asc) }

  def detail_url
    if start_date > Date.today
      if url.blank?
        url_helpers.event_path(self)
      else
        url
      end
    else
      return url_gallery
    end
  end

  def expired?
    start_date < Date.today
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :event

  validates :name,  :phone, presence: true
  validates :email, :email_format => { :message => 'is not looking good' }
  validates :event, presence: true

  validates :company_name, :company_address, :company_tax_id, presence: true, if: 'wht.present?'

  def total
    total = event.price_early_bird * ticket_early_bird
    total += event.price_regular * ticket_regular
    total += event.price_last_ticket * ticket_last_ticket
  end

  def calculate_wht
    (total / 100) * 3
  end

  def grand_total
    if wht
      total - calculate_wht
    else
      total
    end
  end

  def grand_total_satang
    grand_total * 100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  def show
    @order = @event.orders.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_date, :period, :max_price, :low_price, :url)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new(order_params)
    @event = @order.event
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)
    @event = @order.event

    # Charge 1000.00 THB
    charge = Omise::Charge.create({
      amount: 1_000_00,
      currency: "thb",
      card: params[:omiseToken]
    })

    if charge.paid
      # handle success
      puts "thanks"
    else
      # handle failure
      raise charge.failure_code
    end

    respond_to do |format|
      if @order.save
        format.html { render :show, notice: 'Order was successfully create' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def order_params
      params.require(:order).permit(:name, :email, :phone, :condition, :wht, :company_name, :company_address, :company_tax_id, :ticket_early_bird, :ticket_regular, :ticket_last_ticket, :payment_status, :payment_id, :payment_total, :payment_method, :payment_description, :payment_date, :event_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.last(6)
    @alumnis = Alumni.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_ticket.html.erb
<div class="ticket-row">
  <div class="name">
    <%= name %>
  </div>
  <div class="price">
    <%= number_to_currency(price, :unit => "฿ ") %>
  </div>
  <div class="avaliable">
    <%= f.select ticket,
      options_for_select(
        (0..avaliable).each { |n|
          [n,n]
        }, 0), {}, {:class => 'ticket-select'} %>
  </div>
  <div class="description">
    <%= description %>
  </div>
</div>

app/views/events/_tickets.html.erb
<%= form_for order, url: new_order_path, method: "get" do |f| %>
  <%= render partial: "ticket", locals: {
    name: "Early Bird",
    price: @event.price_early_bird,
    ticket: "ticket_early_bird",
    avaliable: 2,
    description: "Pay in 1 day after booking ticket and can not make any cancellation.",
    f:f
  } %>

  <%= render partial: "ticket", locals: {
    name: "Regular",
    price: @event.price_regular,
    ticket: "ticket_regular",
    avaliable: 1,
    description: "Cancellation can be possible 1 month before class.",
    f:f
  } %>

  <%= render partial: "ticket", locals: {
    name: "Last Ticket",
    price: @event.price_last_ticket,
    ticket: "ticket_last_ticket",
    avaliable: 4,
    description: "Cancellation can be possible 1 month before class.",
    f:f
  } %>

  <div class="ticket-row">
    <div class="checkbox">
      <%= f.label :wht do %>
        <%= f.check_box :wht, class: "order-wht" %>
        <strong>Has Withholding Tax</strong> (will plus 3% from total prices)
      <% end %>
    </div>
  </div>

  <div class="ticket-row">
    <div class="note">
      Ticket ทั้ง 3 ต่างกันที่ราคาอย่างเดียวครับ :-)
      โดยราคานี้จะรวมค่าอาหารกลางวัน ขนม และ อุปกรณ์สำหรับ Workshop ทั้ง 2 วัน
    </div>
    <div class="submit">
      <%= f.hidden_field(:event_id) %>

      <%= button_tag type: 'submit', class: "btn btn-success new-order", id: "preview-order-button", disabled: "true" do %>
        <i class="fa fa-ticket" aria-hidden="true"></i>
        Booking
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="event">

  <div id="banner" class="ui">
    <div class="banner-content">
      <div class="banner-text">
        <h1>Speed, UI Workshop</h1>
        <h4>strategic design to make user happiest</h4>
      </div>
    </div>
  </div>

  <div class="event-detail">
    <div class="text-content">
      <%= raw @event.course_description %>
    </div>
  </div>

  <div class="gallery">
    &nbsp;
    <%= raw @event.course_gallery %>
    &nbsp;
  </div>

  <div class="event-detail">
    <div class="text-content">
      <%= raw @event.course_description_2 %>
    </div>
  </div>

  <div class="event-detail">
    <div class="event-ticket">
      <h2>Ticket</h2>
      <%= render "tickets", order: @order %>
    </div>
  </div>

  <div class="event-detail last">
    <div class="text-content">
      มีปัญหาในการจองบัตร ติดต่อ 093-236-0009 (10:00-18:00)
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "shared/head" %>
  <body>
    <%= render "shared/header" %>

    <%= yield %>

    <%= render "shared/footer" %>
    <%= render "shared/foot" %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <strong>
        <%= pluralize(order.errors.count, "error") %>:
      </strong>

      <%= @order.errors.full_messages.map{|m| m}.join(", ") %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name , class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email , class: "control-label" %>
    <%= f.text_field :email, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :phone , class: "control-label" %>
    <%= f.text_field :phone, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :condition, "Memo" , class: "control-label" %>
    <%= f.text_area :condition, class: "form-control"  %>
  </div>


  <% if @order.wht %>

    <h2>Withholding Tax</h2>
    <p>
      Please provide a withholding tax form for

      Kaewkanya Narkjarung (Tax ID: 3102002088075)<br/>
      8/66 moo 6 Salatammasop road<br/>
      Kweng Salatammasop Bangkok 10170
    </p>

    <div class="form-group">
      <%= f.label :company_name , class: "control-label" %>
      <%= f.text_field :company_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :company_address , class: "control-label" %>
      <%= f.text_area :company_address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :company_tax_id, class: "control-label" %>
      <%= f.text_field :company_tax_id, class: "form-control" %>
    </div>

  <% end %>

  <div class="order-ticket">
    <h2>Summary</h2>
    <%= render "tickets", order: @order %>
  </div>

  <div class="payment">
    <h2>Payment form</h2>
    <%= render "payment" %>
  </div>

  <div class="actions">
    <%= f.hidden_field(:event_id) %>
    <%= f.hidden_field(:wht) %>
    <%= f.hidden_field(:ticket_early_bird) %>
    <%= f.hidden_field(:ticket_regular) %>
    <%= f.hidden_field(:ticket_last_ticket) %>

    <%= f.submit "Proceed to payment", id: "submit-payment", class: "btn btn-success submit" %>
  </div>

<% end %>

app/views/orders/_payment.html.erb
<div class="card-wrapper"></div>

<div class="form-group">
  <%= label_tag "Card number" , nil, class: "control-label" %>

  <%= text_field_tag :number, nil,
    class: "form-control",
    placeholder: "Card number",
    :data => {:name => "number" },
    type: "tel" %>
</div>

<div class="form-group">
  <%= label_tag "Name on card" , nil, class: "control-label" %>

  <%= text_field_tag :name, nil,
    class: "form-control",
    placeholder: "Full name",
    :data => {:name => "name" },
    type: "text" %>
</div>

<div class="form-group">
  <%= label_tag "Expiry Date" , nil, class: "control-label" %>

  <%= text_field_tag :expiry, nil,
    class: "form-control",
    placeholder: "MM / YY",
    :data => {:name => "expiry" },
    type: "tel" %>
</div>

<div class="form-group">
  <%= label_tag "Secure code" , nil, class: "control-label" %>

  <%= text_field_tag :cvc, nil,
    class: "form-control",
    placeholder: "123",
    :data => {:name => "cvc" },
    type: "tel" %>
</div>

<input type="hidden" name="omiseToken" />

For bank transfer, business document or more information, please contact Kaewkanya@gmail.com

<%= javascript_include_tag 'https://cdn.omise.co/omise.js' %>

<script>
  new Card({
    form: document.querySelector('form'),
    container: '.card-wrapper',

    formSelectors: {
        numberInput: 'input#number',
        expiryInput: 'input#expiry',
        cvcInput: 'input#cvc',
        nameInput: 'input#name'
    },

    width: 300,
    formatting: true,

    messages: {
      validDate: 'valid\ndate',
      monthYear: 'mm/yy',
    },

    placeholders: {
      number: '•••• •••• •••• ••••',
      name: 'Full Name',
      expiry: '••/••',
      cvc: '•••'
    },

    masks: {
      cardNumber: '•' // optional - mask card number
    },

    debug: false
  });


  Omise.setPublicKey('<%= Omise.public_api_key %>');

  // var checkoutForm = document.getElementById("new_order");
  var checkoutForm = $("#new_order");
  // checkoutForm.addEventListener('submit', submitHandler, false);
  checkoutForm.on('submit', submitHandler);

  // Submit handler for checkout form.
  function submitHandler(event) {
    event.preventDefault();

    var expiry = $('[data-name="expiry"').val();
    var expiry_array = expiry.split(" / ");
    var expiry_month = expiry_array[0];
    var expiry_year = "20" + expiry_array[1];

    var cardObject = {
      name: $('[data-name="name"')[0].value,
      number: $('[data-name="number"')[0].value,
      expiration_month: expiry_month,
      expiration_year:  expiry_year,
      security_code: $('[data-name="cvc"')[0].value
    };

    $('[data-name="number"').val('');
    $('[data-name="cvc"').val('');

    Omise.createToken('card', cardObject, function(statusCode, response) {
      if (statusCode === 200) {
        checkoutForm.find('[name="omiseToken"]').val(response.id);
        checkoutForm.submit();
      }
      else {
        alert(response.message);
      }
    });
  }

</script>

app/views/orders/_ticket.html.erb
<% if ticket_order > 0 %>
  <div class="ticket-row">
    <div class="name">
      <%= name %>
    </div>
    <div class="avaliable">
      <%= ticket_order.round %>
    </div>
    <div class="price">
      <%= number_to_currency(price, :unit => "฿ ") %>
    </div>
    <div class="description">
      <%= description %>
    </div>
  </div>
<% end %>

app/views/orders/_tickets.html.erb
<%= render partial: "ticket", locals: {
  name: "Early Bird",
  price: @event.price_early_bird,
  ticket_order: @order.ticket_early_bird,
  description: "Pay in 1 day after booking ticket and can not do cancellation."
} %>

<%= render partial: "ticket", locals: {
  name: "Regular",
  price: @event.price_regular,
  ticket_order: @order.ticket_regular,
  description: "Cancellation can be possible 1 month before class."
} %>

<%= render partial: "ticket", locals: {
  name: "Last Ticket",
  price: @event.price_last_ticket,
  ticket_order: @order.ticket_last_ticket,
  description: "Cancellation can be possible 1 month before class."
} %>

<% if @order.wht %>
  <div class="summary">
    <div class="name">
      Total
    </div>
    <div class="total">
      <%= number_to_currency(@order.total, :unit => "฿ ") %>
    </div>
  </div>

  <div class="summary">
    <div class="name">
      WHT
    </div>
    <div class="total">
      <%= number_to_currency(@order.calculate_wht, :unit => "฿ ") %>
    </div>
  </div>
<% end %>

<div class="ticket-row">
  <div class="name">
    Grand Total
  </div>
  <div class="total">
    <%= number_to_currency(@order.grand_total, :unit => "฿ ") %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="order">
  <div class="banner"></div>
  <header class="post-header">
    <div class="content">
      <h1>Tickets order</h1>
    </div>
  </header>

  <div class="new-order">
    <div class="content">
      <%= render 'form', order: @order %>
    </div>
  </div>

</div>

app/views/orders/show.html.erb
<div class="order">
  <div class="banner"></div>
  <header class="post-header">
    <div class="content">
      <h1>Your order has been booked</h1>
      <p>
        You will receive email.
      </p>
    </div>
  </header>
</div>

app/views/shared/_facebook_page_plugin.html.erb
<div class="fb-page" data-href="https://www.facebook.com/uxacademy.th/" data-width="300px" data-small-header="false" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/uxacademy.th/"><a href="https://www.facebook.com/uxacademy.th/">UX Academy</a></blockquote></div></div>

app/views/shared/_foot.html.erb
<script>
$(document).ready(function() {

  $("#carousel-alumni").owlCarousel({
    slideSpeed : 300,
    paginationSpeed : 300,
    singleItem: true
  });

  $(function(){
      $(".typed").typed({
          strings: ["HAPPINESS", "TEAM WORK", "WORKFLOW", "INTERFACE", "USABILITY", "INTERACTION", "EXPERIENCE"],
          typeSpeed: 100,
          startDelay: 0,
          backSeed: 1000,
          backDelay: 2000,
          loop: true,
          loopCount: false,
          showCursor: true
      });
  });

});
</script>

app/views/shared/_footer.html.erb
<div class="background-footer" >
  <footer>
    <div class="row">
      <div class="contact">
        <ul class="contact-list">
          <li>
            <p>
              UX Academy is evangelist company.
              We focusing on User Experience design and use understanding
              by the variety of method ex. User Research,
              User Interview, Usability Testing, Data Analytic.
              Our service is Training, Coaching and Consultant.
            </p>
          </li>
          <li>
            <a href="mailto:{{ site.email }}">
              <i class="fa fa-envelope"></i> kaewkanya@uxacademy.in.th
            </a>
          </li>
        </ul>
      </div>

      <div>
        <ul class="social-media-list">
          <li>
            <a href="http://blog.uxacademy.in.th/">
              <i class="fa fa-rss"></i>
              <span class="username">blog.uxacademy.in.th</span>
            </a>
          </li>

          <li>
            <a href="https://github.com/uxacademy">
              <i class="fa fa-github-square"></i>
              <span class="username">uxacademy</span>
            </a>
          </li>

          <li>
            <a href="https://facebook.com/groups/ux.in.th">
              <i class="fa fa-facebook-square"></i>
              <span class="username">Group: groups/ux.in.th</span>
            </a>
          </li>

          <li>
            <a href="https://facebook.com/uxacademy.th">
              <i class="fa fa-facebook-square"></i>
              <span class="username">Page: uxacademy.th</span>
            </a>
          </li>

        </ul>
      </div>

      <div class="description">
        <%= render 'shared/facebook_page_plugin' %>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>UX Academy</title>

  <%= csrf_meta_tags %>

  <meta name="application-name" content="&nbsp;"/>
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/images/site_icons/mstile-144x144.png" />

  <%= favicon_link_tag 'site_icons/favicon.ico' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />
</head>

app/views/shared/_header.html.erb
<header class="site-header">

  <!-- Top Navigation -->
  <nav class="navbar navbar-float-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <div class="logo">&nbsp</div>
          UX Academy
        </a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="https://blog.uxacademy.in.th" onClick="ga('send', {hitType: 'event', eventCategory: 'Blog', eventAction: 'redirect', eventLabel: 'MediumBlog'});">
              Blog
            </a>
          </li>
          <li>
            <a href="/#course">Course Schedule</a>
          </li>
        </ul>
      </div>
      </div>
    </nav>

</header>

app/views/shared/_home_banner.html.erb
<div id="banner">
  <div class="banner-content">
    <div class="banner-text">
      <h1>RE-DESIGN <span class="hightlight dark"><b class="typed">EXPERIENCE</b></span></h1>
      <h4>strategic design to make user happiest</h4>
    </div>
  </div>
</div>

app/views/shared/_home_client.html.erb
<div class="client container">
  <h2>Corporate Customer</h2>
  <p>
    Our customers include many of information architects, graphic designers, service design consultants, web developers, content managers, freelancers and departments inside Thailand’s largest organisations.
  </p>
  <%= image_tag("corporate.png") %>
</div>

app/views/shared/_home_course.html.erb
<div class="course-banner">
  <div id="course" class="course">
    <h2>Course</h2>
    <div class="row">
      <div class="basic">
        <div class="image-content">
          <%= image_tag('basic_banner.png') %>
        </div>
        <div class="text-content">
          <h3>80:20, UX Workshop</h3>
          <p class="dark">
            เน้นความเข้าใจในขั้นตอนการออกแบบประสบการณ์ของผู้ใช้
            ผู้เรียนจะได้เรียนรู้เทคนิคการทำ <b>Customer
            Development การเขียน User Journey และการทำ Usability Test</b> เพื่อที่จะออกแบบโปรแกรมได้ตรงกับใจของผู้ใช้มากที่สุด
          </p>
        </div>
      </div>
      <div class="advance">
        <div class="image-content">
          <%= image_tag('advance_banner.png') %>
        </div>
        <div class="text-content">
          <h3>UX Apply Workshop</h3>
          <p class="dark">
            ทดลองออกแบบ UX Process ด้วยตนเอง
            ผ่านการแนะนำจากทีมงาน และเนื้อหาของบทเรียนที่เน้นประสบการณ์ที่เกิดขึ้นจริงในการใช้ UX ในองค์กรแบบต่างๆ
            เพื่อให้ผู้เรียนสามารถประยุกต์ใช้ได้จริงในหน่วยงานของตนเอง
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_home_schedule.html.erb
<div class="schedule">
  <h2>Schedule</h2>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th class="class-name">Course</th>
        <th class="date">Dates</th>
        <th class="price">Price</th>
        <th class="price">Early Bird</th>
        <th>Book &amp; Detail</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td class="class-name">
            <%= event.name %>
            <div class="date-name"><%= event.start_date.strftime("%e %B %Y") %></div>
          </td>
          <td class="date"><%= event.start_date.strftime("%e %B %Y") %></td>
          <td class="price">
            <%= number_to_currency(event.max_price, :unit => "฿ ") %>
          </td>
          <td class="price">
            <%= number_to_currency(event.low_price, :unit => "฿ ") %>
          </td>
          <td class="detail <%= event.expired? ? "expired" : "alive" %>">
            <a class="btn" href="<%= event.detail_url %>">
              <i class="fa"></i>
              <% if event.expired? %>
                <%= event.category.upcase %> Gallery
              <% else %>
                More detail
              <% end%>
            </a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="inhouse-contact" >
  <h4 class="note">
    For Inhouse workshop, please contact
    <a href="tel:083-236-0009">083-236-0009</a> or
    <a href="mailto:kaewkanya@uxacademy.in.th">kaewkanya@uxacademy.in.th</a>
  </h4>
</div>

app/views/shared/_home_service.html.erb
<div class="services">
  <div class="row">
    <div class="overview">
      <h2>Service</h2>
      <p>
        UX Academy เปิดบริการให้คำปรึกษาแก่ บริษัทที่พัฒนา Web หรือ Desktop/Mobile Application ทั้งบริษัท Enterprise และ StartUp ในด้านต่างๆ ดังนี้
      </p>
    </div>
    <div class="service">
      <%= image_tag('icon_coach.png') %>
      <h3>UX Coaching</h3>
      <p>
        ร่วมกับทีมในการวิเคราะห์<br/>
        ความต้องการของผู้ใช้<br/>
        และ <b>พัฒนา UX Process<br/>
        ที่เหมาะกับองค์กร</b>
      </p>
    </div>
    <div class="service">
      <%= image_tag('icon_test.png') %>
      <h3>Usability Test</h3>
      <p>
        วิเคราะห์ UI รวมไปถึง Persona <br/>
        และ User Journey ของบริษัทผ่าน<br/>
        การทดสอบกับผู้ใช้จริง<br/>
      </p>
    </div>
    <div class="service">
      <%= image_tag('icon_design.png') %>
      <h3>UX Design</h3>
      <p>
        ใช้กระบวนการของ UX <br/>
        เพื่อออกแบบโปรแกรมบนมือถือ<br/>
        เว็บไซต์ และบริการ <br/>
        ที่จะทำให้ผู้ใช้รัก
      </p>
    </div>
  </div>
</div>

app/views/shared/_home_testimonial.html.erb
<div class="testimonial-background">
  <div class="testimonial">
    <div class="row">
      <h2>Testimonial</h2>
      <div class="col-md-12">
        <div id="carousel-alumni" class="owl-carousel">
          <% @alumnis.each do |member| %>
            <div class="item">
              <div class="alumni">
                <p class="dark">
                  <%= member.feedback.html_safe %>
                </p>
                <div class="profile">
                  <%= image_tag "alumni/#{member.photo}" %>
                  <div class="profile-text">
                    <%= member.name %><br/>
                    <span class="company">
                      <%= member.position %> <br/>
                      <a href="<%= member.company_url %>">
                        @ <%= member.company %>
                      </a>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_home_ux_is.html.erb
<div class="uxis">
  <div class="text-content">
    <h2>การเข้าใจ UX</h2>
    <p>
      คือการเข้าใจผู้ใช้อย่างลึกซึ้ง ไม่ใช่แค่ผู้ใช้ต้องการทำอะไร แต่มองให้รู้ว่าทำไมถึงต้องการแบบนั้น
      ถ้าสามารถเข้าใจได้ ก็จะช่วยลดความเสี่ยงในการออกแบบ
      ลดเวลาในการพัฒนา และช่วยให้โปรแกรมตอบโจทย์ผู้ใช้อย่างแท้จริง
    </p>
  </div>
  <div class="image-content">
    <%= image_tag('wireframe_1_160.png') %>
    <%= image_tag('wireframe_2_160.png') %>
    <%= image_tag('wireframe_3_160.png') %>
  </div>
</div>

app/views/shared/_tickets.html.erb
<%= render partial: "shared/ticket", locals: {
  name: "Early Bird",
  price: @event.price_early_bird,
  avaliable: 3,
  description: "Pay in 1 day after booking ticket and can not make any cancellation."
} %>

<%= render partial: "shared/ticket", locals: {
  name: "Regular",
  price: @event.price_regular,
  avaliable: 1,
  description: "Cancellation can be possible 1 month before class."
} %>

<%= render partial: "shared/ticket", locals: {
  name: "Last Ticket",
  price: @event.price_last_ticket,
  avaliable: 4,
  description: "Cancellation can be possible 1 month before class."
} %>

<div class="ticket-row">
  <div class="note">
    Ticket ทั้ง 3 ต่างกันที่ราคาอย่างเดียวครับ :-)
    โดยราคานี้จะรวมค่าอาหารกลางวัน ขนม และ อุปกรณ์สำหรับ Workshop ทั้ง 2 วัน
  </div>
  <div class="submit">
    <%= link_to new_order_path(:event => @event.id),
      class: "new-order" do %>
      <i class="fa fa-ticket"></i>
      Booking
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="home">
  <%= render "shared/home_banner" %>
  <%= render "shared/home_ux_is" %>
  <%= render "shared/home_course" %>
  <%= render "shared/home_schedule" %>
  <%= render "shared/home_service" %>
  <%= render "shared/home_testimonial" %>
  <%= render "shared/home_client" %>
</div>